apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "nirn-proxy.fullname" .) }}
  labels:
    {{- include "nirn-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.clusterPort }}
      targetPort: cluster
      protocol: TCP
      name: cluster
  selector:
    {{- include "nirn-proxy.selectorLabels" . | nindent 4 }}
